# Generated by Django 4.1 on 2025-05-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografias_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('GPT', 'gpt'),
                    ('VIDEOS', 'videos'),
                    ('IMAGENS', 'imagens'),
                    ('AUDIOS', 'audios'),
                ],
                default='',
                max_length=100,
            ),
        ),
    ]
