# Generated by Django 4.1 on 2025-05-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografias_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('GPT', 'gpt'),
                    ('VIDEOS', 'videos'),
                    ('IMAGENS', 'imagens'),
                    ('AUDIOS', 'audios'),
                    ('DADOS', 'dados'),
                    ('DESIGN', 'design'),
                    ('UTILITARIOS', 'utilitarios'),
                ],
                default='',
                max_length=100,
            ),
        ),
    ]
